TECHDOCS-1157 add instructions examples
ngross71/maps-api-for-javascript-examples pull request #1
Opened 2022-05-11 10:30 UTC by ngross71

2022-05-12 08:07 UTC, kplotnik requested changes

2022-05-12 08:07 UTC, kplotnik commented on README.md
> +Download all files in the GitHub folder linked to the "Fork on GitHub" button on the top of the example page. Additionally, download the **test-credentials.js** file, the **template.css** file and th
This Readme is available on gihub only. Why do we send the user back to developer.here.com? Besides, I presume, that we talk to developers here who understand what is Git - so I'd expect to see here the instructions in the spirit clone the repository, host it on your local server (or npx serve) and replace credentials

2022-05-16 07:34 UTC, kplotnik commented
Looks good to me, thank you.

2022-05-17 14:47 UTC, merged

2022-05-17 14:48 UTC, ngross71 commented
@kplotnik unfortunately I don't have rights to merge to the master repo. Can you merge my commit from my fork to the master repo? Thank you